M48
; DRILL file {KiCad 7.0.2} date Sat May 20 11:27:27 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-20T11:27:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X2.26Y-3.11
X2.26Y-4.89
X3.2Y-2.14
X3.2Y-5.86
T2
X2.3901Y-4.1398
X2.3901Y-4.6398
X2.3902Y-3.3599
X2.3902Y-3.8599
T0
M30
